### ISSUE TITLE
[UserTrait] Add helper functions

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-members#105]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

I just implemented some helper functions (`hasGroup`, `addGroup`, `removeGroup`) to my user class on one of my projects and thought that those would be a great addition to Members. I saw that `hasGroup` already exists in the `UserTrait`, but compares the groups by name. IMHO it should compare ID's.

If you're interested, I could contribute those helper functions by providing a PR.
@solverat WDYT?

**Comment by solverat** [comment]
Hey @aarongerig,

The `hasGroup` requires the groupname which seems ok to me and introduces a BC if we're going to change it to ID. But we could introduce a new method `hasGroupId` for example? Further we could add another method `hasGroupName` and deprecate the `hasGroup` method.

`AddGroup(GroupInterface)` and `RemoveGroup(GroupInterface)` sounds good to me!

Branch: `dev-master` (only P6), I suppose.

**Comment by aarongerig** [comment]
Sounds good, I'll prepare the PR.

**Comment by solverat** [comment]
@aarongerig are we done here?

**Comment by aarongerig** [comment]
Yes, I‘ll close the issue.
