### ISSUE TITLE
Wrong conditions in Class MembersBundle\Manager\RestrictionManager

### ISSUE THREAD

**Issue by kathangeorg** [dachcom-digital/pimcore-members#115]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

`} elseif ($element instanceof DataObject) {` should be 
`} elseif ($element instanceof DataObject\Concrete) {` in functions
`getElementRestrictedGroups(...)` and `getElementRestrictionStatus(...)` because Custom Objects extend `Pimcore\Model\DataObject\Concrete`.

Otherwise the condition does (not) match randomly in my current project.

**Comment by solverat** [comment]
fixed with #116
