### ISSUE TITLE
[SSO] Instant User: Password Definition

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-members#121]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

## Change Password
If a user directly gets connected with a client, he's currently not able to define a password because he needs is current password which is not available. 

We could implement a `ChangePasswortTypeExtension` class to remove the `current_password` field.

@aarongerig: WDYT?

**Comment by aarongerig** [comment]
It should be possible to choose from two options.

1. Connect to a client and instantly be logged in without any supplementary information gathered by a form (no password).
2. Connect to a client and gather some additional information from the user with a registration form (e.g. password). Example: https://www.woche-pass.ch/anmelden

I haven't tried the Members OAuth implementation on that website yet, but will soon. If I understood correctly, currently option 2 wouldn't be possible, correct? If so, your proposal sounds about right. 👍

**Comment by solverat** [comment]
@aarongerig this is already possible:

1: `members.oauth.activation_type: 'instant` 
2: `members.oauth.activation_type: 'complete_profile'`

But in both cases he's allowed to enter a valid authentication state without any given password!

We may should implement a custom `SetPasswortTypeFormType` (instead of modifying the `ChangePasswortFormType`) which only should be available if a user does not have a password.

**Comment by aarongerig** [comment]
I see, then the custom form type should only be available, if the user doesn't have a password **and** has an SSO identity connected to it (just to make sure), right?

**Comment by solverat** [comment]
yes!

Also: We cannot detect users email address automatically because it's hidden in `getResourceOwner()->toArray()` and each client is allowed to define their own logic there.

So currently, an `instant` login will create a user + identitiy, that looks like this:

![image](https://user-images.githubusercontent.com/700119/69042285-3e95e280-09f1-11ea-8f5d-143e9fbd63d9.png)

You're able to add some data via [resource mapping](https://github.com/dachcom-digital/pimcore-members/blob/master/docs/SSO/12_ResourceMapping.md) but sometimes the client can't or won't provide any personal data.

The more I think about it, I think we just should provide a transformer form (e.g. `SsoTransformerFormType`), which allows to transform an identity to a real user. Per default, it comes with a password (if no password has been set already) and an email address  (if no email address has been set already) field. You're able to add more with a custom form extension.

**Comment by solverat** [comment]
## Instant SSO Identity Profile
![image](https://user-images.githubusercontent.com/700119/75279916-c2d7dd00-580c-11ea-9f19-5d326a1d69b0.png)

## Complete Profile
![image](https://user-images.githubusercontent.com/700119/75280238-5e694d80-580d-11ea-84de-750c144cde92.png)
