### ISSUE TITLE
Updated to Pimcore 6.3 - members broke

### ISSUE THREAD

**Issue by justbane** [dachcom-digital/pimcore-members#127]
After updating to Pimcore 6.3 I now revieve this error on all pages.

```Argument 1 passed to MembersBundle\Document\Builder\BrickBuilder::__construct() must be an instance of Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage, instance of Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage given, called in /local/htdocs/.../var/cache/local/Container2PLYfpj/getMembers_Area_Brick_LoginService.php on line 18```

All caches have been cleared (even hard cleared by deleting the files) I have tried to uninstall/reinstall/enable/disable members - nothing works

**Comment by Roizan** [comment]
Same here - still figuring out if the update to 6.x was the issue

**Comment by AndiKeiser** [comment]
@justbane, @Roizan Downgrade from Symfony 4.4.x to 4.3.9

**Comment by solverat** [comment]
This has been fixed within https://github.com/dachcom-digital/pimcore-members/pull/123 and will be available in the next release (3.1.0)

**Comment by justbane** [comment]
Thank you!!

––
Justin Bane
cell: 916-712-2194
justbane@gmail.com
––––––––––––––––––––
www.justinbane.com
