### ISSUE TITLE
[Group Multiselect] Update to Pimcore 6.5 breaks

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-members#129]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

I'm pretty sure Pimcore messed up again with their latest releases. Once I update to Pimcore 6.5.0 or higher, the group multiselect data type doesn't function properly anymore. It returns an empty array event though there is data in the database. Saving and/or reading data to/from the database also doesn't work.

@solverat  Can you confirm that issue?

**Comment by solverat** [comment]
Confirmed. I'll check it.

**Comment by aarongerig** [comment]
Thanks!
