### ISSUE TITLE
Issues with user registering

### ISSUE THREAD

**Issue by Senexis** [dachcom-digital/pimcore-members#13]
I'd like to report 2 issues I have with the plug-in, which makes it totally unusable for me (what good is a members plug-in when I can't create members?):

- Whenever I'm creating a member through front-end, I get the error `ParentID and ID is identical, an element can't be the parent of itself`.
- Whenever I'm creating a member through back-end, for whatever reason, the member object is not found when trying to log in. Resetting the password works fine, but whenever I log in, I get `\Zend_Auth_Result::FAILURE_IDENTITY_NOT_FOUND`.

I'm not sure what you would need to help resolving this issues, so please let me know.

**Comment by solverat** [comment]
Couldn't reproduce this. Please add some more information (version, pimcore5?) Also note, that the pimcore4 Version is no longer supported. Feel free to reopen it.
