### ISSUE TITLE
authenticate user through REST-api in a SPA (single-page application)

### ISSUE THREAD

**Issue by thgross** [dachcom-digital/pimcore-members#132]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Hi there,

How would I use the pimcore-members back-end without the provided forms?

We are currently developing a react application and want to use pimcore and pimcore-members for all back-end stuff. However, I could not find any information on how to use pimcore-members back-end functionality through a REST api.

Is this possible? What would be the best way to achieve this?

Thank you!

**Comment by solverat** [comment]
Since members is just using the symfony security principals, you should be able to extend the existing installation. It would require a new (stateless) firewall with some handler (JWT for example) and the existing members user provider.

I'm afraid I can't give you any further help for now.
