### ISSUE TITLE
[AWS S3] Incompatibility when installing

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-members#137]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

## Description
When installing the members bundle on a Pimcore instance connected to an AWS S3 Bucket following exception is thrown:

```log
User Warning: Mode not supported: w+. Use one 'r', 'w', 'a', or 'x'.
```

This happens because the members bundle tries to create the folder `/restricted-assets` with a `.htaccess` file in it via the [`fopen()` function with a mode of `w+`](https://github.com/dachcom-digital/pimcore-members/blob/master/src/MembersBundle/Tool/Install.php#L294). This is not supported by the AWS SDK ([code](https://github.com/aws/aws-sdk-php/blob/master/src/S3/StreamWrapper.php#L579-L582) and [documentation](https://docs.aws.amazon.com/aws-sdk-php/v2/guide/feature-s3-stream-wrapper.html#uploading-data)).

### Possible solution
What would happen if members bundle tries to only write the file with mode `w`? Could this be a possible solution to this? Or is there an explicit reason for the `w+`?

@solverat What do you think?

**Comment by aarongerig** [comment]
Ping @solverat :)

**Comment by solverat** [comment]
@aarongerig I think there is no need for the `w+` since we don't need to read the file, I'll change it to the single `w`!
