### ISSUE TITLE
[GroupMultiselect] Dependencies are not resolved

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-members#139]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

## Description
In a member object you can select a member group object. Unfortunately as of now the dependency to that object is not resolved and doesn't get saved to the DB.

Would it be possible to add the dependency resolver method to the multiselect extension?

Maybe something like:
```php
/**
 * @param Element\AbstractElement|null $data
 *
 * @return array
 */
public function resolveDependencies($data)
{
    $dependencies = [];

    if ($data instanceof Element\ElementInterface) {
        $elementType = Element\Service::getElementType($data);
        $dependencies[$elementType . '_' . $data->getId()] = [
            'id' => $data->getId(),
            'type' => $elementType
        ];
    }

    return $dependencies;
}
```

**Comment by aarongerig** [comment]
WDYT @solverat ?

**Comment by solverat** [comment]
@aarongerig I think this is the same issue (if I got you right): https://github.com/dachcom-digital/pimcore-members/issues/140

**Comment by aarongerig** [comment]
@solverat Thanks for looking into this! Actually not quite, let me make an example. Let's say we have a `MemberGroup` object, which gets assigned to a `Member` object via the `GroupMultiselect` data type. The `MemberGroup` then should be listed as dependency in the dependency tab in the `Member` object (see screenshot below). Right now this does not happen.

![dependencies](https://user-images.githubusercontent.com/17384333/84027055-aa8c6800-a98e-11ea-9e48-f6d95b9d2d4b.png)

**Comment by solverat** [comment]
AH! Right! Let's fix that.
