### ISSUE TITLE
Can not set group after Update: This does not work any more.

### ISSUE THREAD

**Issue by a4chris** [dachcom-digital/pimcore-members#140]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi Stefan

After Updating a Project to "Pimcore": ~6.6.5 and "members": "~3.1.2" is it not possible to set the Multiselect "groups" in Class "MembersUser" programmatically anymore.

Either like this:
config.yml
members:
    restriction:
        enabled: true
    user:
        initial_groups:
            - 4
    post_register_type: 'confirm_instant' 
    send_admin_mail_after_register: false
    send_user_mail_after_confirmed: false
    
    
nor like this:
	$object = new DataObject\MembersUser(); 
	$object->setKey(\Pimcore\File::getValidFilename($key));
	$object->setParentId($parentId);
	$object->setPublished(true);
	$object->setGroups([DataObject\MembersGroup::getById(4)]);
 $object->save();

Is this is a known issue?
Thanks for helping.
Christoph

**Comment by solverat** [comment]
You're right - fixed with https://github.com/dachcom-digital/pimcore-members/commit/e597744919dcd14926ae5ae81e979cabe671bead!

**Comment by solverat** [comment]
Don't forget to apply `bin/console pimcore:migrations:migrate -b MembersBundle`after updating!

**Comment by a4chris** [comment]
Hi Stefan
Installed, Tested, Worked!
Thank you ver much.
