### ISSUE TITLE
[Feature Request] Add specific settings for GroupMultiselect data type

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-members#143]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Add some specific settings for the GroupMultiselect data type, e.g. same as Pimcore does it natively for the Multiselect data type (see screenshot below).

![specific_settings](https://user-images.githubusercontent.com/17384333/85987037-6587ae80-b9ed-11ea-8eec-4ae2f63c43ca.png)

Especially the render type would be really helpful if you have hundreds/thousands of groups to select from.

**Comment by solverat** [comment]
Good one.
