### ISSUE TITLE
Getting Errors using RestrictionUri or RestrictionManager

### ISSUE THREAD

**Issue by a4chris** [dachcom-digital/pimcore-members#144]
Hi Stefan

Getting Errors when I use RestrictionUri or RestrictionManager:

Testcode:
use MembersBundle\Security\RestrictionUri;
use MembersBundle\Manager\RestrictionManager;

$download = \Pimcore\Model\Asset::getById(488);
$downloadLink = $this->container->get(RestrictionUri::class)->generateAssetUrl($download);
// ERROR -> MembersBundle\Security\RestrictionUri" not found: the container inside "Symfony\Component\DependencyInjection\Argument\ServiceLocator

$element = Pimcore\Model\Asset::getById(1);
$restriction = $this->container->get(RestrictionManager::class)->getElementRestrictionStatus($element);
// ERROR -> MembersBundle\Manager\RestrictionManager" not found: the container inside "Symfony\Component\DependencyInjection\Argument\ServiceLocator

Pimcore 6.6.9, MembersBundle 3.1.3

Need Help Please. Thank You so much.

**Comment by solverat** [comment]
Hey @a4chris using the container to get services is a not preferred way, I just updated the docs accordingly: https://github.com/dachcom-digital/pimcore-members/blob/master/docs/240_AssetProtection.md

**Comment by a4chris** [comment]
Hi Stefan

I will review!


Thanks a lot and Stay Healthy

 

LG Christoph

 

 

A4 AGENTUR AG

Markenführung / Design / Kommunikation

 

Christoph Kohler

Leiter Digitale Medien

Tel. direkt 041 798 30 29

christoph.kohler@a4agentur.ch

 

Grundstrasse 14 
6343 Rotkreuz

Tel. 041 798 30 20

www.a4agentur.ch

 

 

Von: Stefan Hagspiel <notifications@github.com>
Antworten an: dachcom-digital/pimcore-members <reply@reply.github.com>
Datum: Freitag, 15. Januar 2021 um 09:49
An: dachcom-digital/pimcore-members <pimcore-members@noreply.github.com>
Cc: Christoph Kohler <christoph.kohler@a4agentur.ch>, Mention <mention@noreply.github.com>
Betreff: Re: [dachcom-digital/pimcore-members] Getting Errors using RestrictionUri or RestrictionManager (#144)

 

Hey @a4chris using the container to get services is a not preferred way, I just updated the docs accordingly: https://github.com/dachcom-digital/pimcore-members/blob/master/docs/240_AssetProtection.md

**Comment by a4chris** [comment]
Lieber Stefan 

Gibt es eine Möglichkeit, das geniale MembersBundle mit Pimcore 6.9.6 zu verwenden?
Ich brauche für ein Projekt das MembersPlugin und den Datahub (benötigt Pimcore 6.9)
Im Backend scheint alles zu funktionieren, aber im Frontend erhalte ich eine Fehlermeldung.
Siehe Screenshots!


Vielen Dank für Deine Antwort.
Lieber Gruss
Christoph

 

 

//////////////////////////

 

Kohler Digital

Gesegnetmattstrasse 1

6006 Luzern

 

Phone: 041 678 00 66

Mobile: 076 761 17 97

***@***.***

www.kohler-digital.ch

 

//////////////////////////

 

 

 

Von: Christoph ***@***.***>
Datum: Freitag, 15. Januar 2021 um 10:42
An: dachcom-digital/pimcore-members ***@***.***>
Betreff: Re: [dachcom-digital/pimcore-members] Getting Errors using RestrictionUri or RestrictionManager (#144)

 

Hi Stefan

I will review!

Thanks a lot and Stay Healthy

 

LG Christoph

 

 

A4 AGENTUR AG

Markenführung / Design / Kommunikation

 

Christoph Kohler

Leiter Digitale Medien

Tel. direkt 041 798 30 29

***@***.***

 

Grundstrasse 14 
6343 Rotkreuz

Tel. 041 798 30 20

www.a4agentur.ch

 

 

Von: Stefan Hagspiel ***@***.***>
Antworten an: dachcom-digital/pimcore-members ***@***.***>
Datum: Freitag, 15. Januar 2021 um 09:49
An: dachcom-digital/pimcore-members ***@***.***>
Cc: Christoph Kohler ***@***.***>, Mention ***@***.***>
Betreff: Re: [dachcom-digital/pimcore-members] Getting Errors using RestrictionUri or RestrictionManager (#144)

 

Hey @a4chris using the container to get services is a not preferred way, I just updated the docs accordingly: https://github.com/dachcom-digital/pimcore-members/blob/master/docs/240_AssetProtection.md
