### ISSUE TITLE
User is set to null when changing Role/Group

### ISSUE THREAD

**Issue by polelo** [dachcom-digital/pimcore-members#146]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi,

Loving the members bundle, super resourceful.

After migrating to pimcore 6.7.0 and members 3.1.0 I'm being logged out on the front-end whenever I update the member Role/group in pimcore admin. 

I'm using the below code in my homepage once I'm logged in:
$user = $this->app->getUser(); 
var_dump($user);
exit;
When I go to pimcore admin/back-end and update the current user's role/group then press Save & Publish, the value of $user becomes null.
This never happen with the previous versions.

Thanks.

**Comment by solverat** [comment]
@polelo fixed? 😁

**Comment by polelo** [comment]
@solverat 2 years later after upgrading to pimcore-x I find myself back here 😁
