### ISSUE TITLE
Can't save Model with inherited restriction rules

### ISSUE THREAD

**Issue by foxgreek** [dachcom-digital/pimcore-members#162]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If I inherit the restriction rules to the children, following error occurs while trying to save children:
![image](https://user-images.githubusercontent.com/40141606/144847951-25ef749f-6b9a-47bd-8437-c77051b92bd8.png)

Affected file: **src/MembersBundle/Controller/Admin/RestrictionController.php**

It can be fixed by adding a **null coalescing operator to line 126**:

`$groups = array_filter(explode(',', $settings['membersDocumentUserGroups'] ?? ''));`

**Comment by solverat** [comment]
fixed with #163. 4.0.1 has been released!
