### ISSUE TITLE
[Members2] Implement Guard Authenticator for Crawler

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-members#17]
Allow site crawler like [LuceneSearch](https://github.com/dachcom-digital/pimcore-lucene-search/) to crawl restricted routes/assets by adding a `X-AUTH-TOKEN` for example.

**Comment by mediafant** [comment]
It looks as you can read minds - thanks !

**Comment by solverat** [comment]
remove token guardian. this is could be easily done in a specific project. just add some information and examples to the readme.
