### ISSUE TITLE
Pimcore 11 Compatibility

### ISSUE THREAD

**Issue by ChrisB9** [dachcom-digital/pimcore-members#176]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Is there going to be a roadmap for v11 and symfony 6.2 ?

**Comment by solverat** [comment]
Hey @ChrisB9. We don't have a time based roadmap but there will be definitly a v5 with p11 support.

BTW: We never had good experiences with fresh pimcore releases (they are mostly stable within x.1 / x.2 minor releases).

**Comment by ChrisB9** [comment]
Alright, good to know. I actually don't even think it should be too much stuff that has changed on symfonys side. I am using the members-bundle already with the new authentication system and it runs very smoothly, only had to adjust a couple little things in my securty config

Yea, absolutely. I am preparing to update with the .1 release, but due to my large codebase I have to plan and prepare everything :)

**Comment by solverat** [comment]
@ChrisB9 Just for the record: 4.1 has been released today, which natively supports the new authentication system!

**Comment by solverat** [comment]
dev-master is ready for p11.
