### ISSUE TITLE
There's a bug in src/Adapter/User/UserTrait.php line 56 where it just breaks when you have an empty roles. 

### ISSUE THREAD

**Issue by willfroq** [dachcom-digital/pimcore-members#199]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes
| RFC?             | yes/no

**Comment by willfroq** [comment]
The fix would be just: `foreach ($this->getGroups() ?? [] as $group) {` 
![Screenshot 2024-03-10 at 09 31 18](https://github.com/dachcom-digital/pimcore-members/assets/150448078/15571f49-d633-467d-98f3-1a0ab287eb6e)

**Comment by blankse** [comment]
@willfroq I created a PR: https://github.com/dachcom-digital/pimcore-members/pull/200

**Comment by scrummer** [comment]
resolved by #200
