### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-members#204]
Dear Contributors, 

we're currently working on dual licensing this bundle (under GPLv3 and DCL [`DACHCOM Commerce License`]) to be compatible with Pimcore Enterprise and Professional. In order to do that, we need your approval (contributor license agreement). The agreement can be found here: https://github.com/dachcom-digital/pimcore-members/blob/master/CLA.md

We therefore kindly ask the following persons to sign the CLA by **writing the following sentence as a comment under this issue**:

`I have read the CLA Document and I hereby sign the CLA`

- [x] @aarongerig
- [x] @scrummer
- [x] @LosHawlos
- [x] @ktallafus
- [x] @dpfaffenbauer
- [x] @lorextera
- [x] @youwe-petervanderwal
- [x] @kjkooistra-youwe
- [x] @dasraab
- [x] @blankse
- [x] @kathangeorg
- [x] @mittererr
- [x] @geekdevs
- [x] @pascalmoser
- [x] @lukas-schnieper
- [x] @Cruiser13
- [x] @jdreesen
- [x] @GALCF

**Comment by jdreesen** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bitbirddev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by blankse** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lukas-schnieper** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by youwe-petervanderwal** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by scrummer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pascalmoser** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by GALCF** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kjkooistra-youwe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ktallafus** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by solverat** [comment]
Cheery ping to @LosHawlos, @dpfaffenbauer, @lorextera, @dasraab, @kathangeorg, @mittererr, @geekdevs

**Comment by bitbirddev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dasraab** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by LosHawlos** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dpfaffenbauer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mittererr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lorextera** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kathangeorg** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by geekdevs** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by solverat** [comment]
Thanks to all of you for your help! ❤️
