### ISSUE TITLE
OAuth Connector

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-members#21]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

- add bridge
- add example

**Comment by AndiKeiser** [comment]
Is this bridge still under consideration in further development?

**Comment by aarongerig** [comment]
Actually would be interested as well. Any updates on this, @solverat ?

**Comment by solverat** [comment]
Well... no. 😄 I created this issue shortly before pimcore released there CMF (which also comes with the oAuth-Bundle).

Some users are using members in combination with the CMF, so we need to ensure the compatibility. So my main questions are:

- Should we make this totally optional? 
- Implement it more or less the same way as the CMF does? (Just a bit more convenient 😄)

**Comment by solverat** [comment]
Ok, I think I found a solution. I'll provide a PR the next days.

**Comment by aarongerig** [comment]
I am using members in combination with the CMF. To make it work with SSO authentication I had to do the following.

1. Configure the HWIOAuthBundle and add some security stuff to the members firewall.

```yml
firewalls:
    members_fe:
        anonymous: ~
        provider: cmf
        oauth:
            resource_owners:
                facebook: app_auth_oauth_check_facebook
                google: app_auth_oauth_check_google
            login_path: members_user_security_login
            failure_path: members_user_security_login
            default_target_path: app_portal_dashboard
            oauth_user_provider:
                service: cmf.security.user_provider.oauth
```

2. Overwrite the `AuthController` to save the OAuthToken in the session and redirect to the registration page.

```php
if ($error instanceof AccountNotLinkedException) {
    $token = $error->getToken();

    if ($token instanceof OAuthToken) {
        $registrationKey = Uuid::uuid4();
        $oAuthHandler->saveToken($registrationKey, $token);

        return $this->redirectToRoute('members_user_registration_register', [
            'registrationKey' => $registrationKey
        ]);
    }
}
```

3. Overwrite the RegistrationController to load the OAuthToken via passed `registrationKey` and merge/pass the user information to the registration form.

```php
$oAuthToken = $oAuthUserInfo = null;
if (
    null !== ($registrationKey = $request->get('registrationKey')) &&
    null !== ($oAuthToken = $oAuthHandler->loadToken($registrationKey))
) {
    $oAuthUserInfo = $oAuthHandler->loadUserInformation($oAuthToken);
}

$isSSO = null !== $oAuthUserInfo;

if (null !== $oAuthUserInfo && $oAuthHandler->getCustomerFromUserResponse($oAuthUserInfo)) {
    throw new RuntimeException('Customer is already registered');
}

$formData = $user;
if (null !== $oAuthToken) {
    $formData = $this->mergeOAuthFormData($formData, $oAuthUserInfo);
}

$form = $this->formFactory->createForm(['is_sso' => $isSSO]);
$form->setData($formData);
```

4. After a successful form submission the SSO Identity is created and connected to the user object.

```php
if (null !== $oAuthUserInfo) {
    $oAuthHandler->connectSsoIdentity($user, $oAuthUserInfo);
}
```

5. If the form submission wasn't successful, we have to "resave" the OAuthToken to the session, since the CMF removes the token once it is loaded (?! 🙄).

```php
if ($oAuthToken) {
    $oAuthHandler->saveToken($registrationKey, $oAuthToken);
}
```

6. Finally, I had to create a compiler pass, which removes the `MembersBundle\EventListener\PostConfirmationListener` and replaced it with my own custom event listener. Reason: The regular registration process should trigger the email confirmation workflow. If the user registers via SSO though, the account has to be confirmed immediately and redirect the user to the dashboard page.

If you need more detailed info, let me know.

**Comment by solverat** [comment]
Yes - that's more or less the same i implemented.

## RoadMap

### Installation

```yml
members:
    oauth:
        enabled: true
```

### Command
- Provide a command `members:enable-oauth`, which will check some stuff:
  - `ssoIdentities` field added to user class? (If not, add it: `yes/no`)?
  - SSO Identity Class installed? (If not, add it: `yes/no`)?
  - Objectbricks (oauth1, oauth2) installed? (If not, add it: `yes/no`)?
  - Check if `HttplugBundle` and `HWIOAuthBundle` is available and enabled (needs to be done in `AppBundle`)
  - Check if user class has an implemented `SsoAwareCustomerInterface`

- Add a How-To Documentation Page:
  - `security` config example
  - `hwi_oauth` config example
  - `pimcore.encryption.secret` example (We don't use the crazy encryption service like CMF - instead i used `encryptedField` field for sensetive data in all object bricks

## Questions
- Currently, the user needs to "finalize" his registration (without password). There is no - "one-click-redirect-and-logged in" process. I think that's fine - right?
- Do we need some data mapping? (like, which fields from `UserResponse` should get applied to which fields of the user object (example: `[firstname => name, email => emailAdress]`)? Maybe a yml config per resource owner?
- After the registration form has been successfully submitted: Publish the user, fire a custom event (like `MembersEvents::SSO_REGISTRATION_SUCCESS`) and immediately redirect user to dashboard or whatever page?

**Comment by solverat** [comment]
hey @aarongerig, @AndiKeiser: I just raised the oauth PR to "almost done" 😄: 

https://github.com/dachcom-digital/pimcore-members/tree/oauth

I would LOVE to hear your opinion!

I also added some docs, so it should be quite easy to install this feature: 

Overview: https://github.com/dachcom-digital/pimcore-members/tree/oauth#single-sign-on-sso-with-oauth2

Installation: https://github.com/dachcom-digital/pimcore-members/blob/oauth/docs/SSO/20_Installation.md

**Comment by aarongerig** [comment]
Hi @solverat

Nice job, looks great! I will test it as soon as I get back to that project, where I have OAuth enabled. I will try to implement it the "members way". ;)

You'll hear from me.

**Comment by solverat** [comment]
@aarongerig merged into master. I'll create some follow-up stories to keep this structured.
