### ISSUE TITLE
Cannot install with console

### ISSUE THREAD

**Issue by geekdevs** [dachcom-digital/pimcore-members#25]
Cannot install this extension with console. I see this error:

`No entry is registered for key 'pimcore_admin_user'`

Testing on fresh installation of pimcore 5, build 108.
And latest dev master of this extension (https://github.com/dachcom-digital/pimcore-members/commit/c5c78a3fc23ac2435727bbaca5c86073b7bd37b7)

Steps to reproduce:
- `composer require dachcom-digital/members:dev-master#c5c78a3fc23ac2435727bbaca5c86073b7bd37b7`
- `bin/console pimcore:bundle:enable MembersBundle`
- `bin/console cache:clear`
- `bin/console pimcore:bundle:install MembersBundle`

**Comment by geekdevs** [comment]
@solverat would you advice versions on which this plugin works? I understand everything's on alpha here and quite unstable, but what do you test with?
So far I failed to find pimcore build + members plugin combination which would work together.

**Comment by solverat** [comment]
Currently we try to keep on track with the newest pimcore build. Since they're changing a lot within the last builds we're doing our best to stay stable whenever it's possible. You'll find the current  compatible pimcore build in every [readme](https://github.com/dachcom-digital/pimcore-members#requirements) of our bundles. 

Testing: Always the latest build of pimcore5.

cheers, stefan.

**Comment by geekdevs** [comment]
@solverat thanks for fixing this quickly. Regarding versions - I tried the following:
Testing on fresh installation of pimcore 5, build 108.
And latest dev master of this extension (https://github.com/dachcom-digital/pimcore-members/commit/c5c78a3fc23ac2435727bbaca5c86073b7bd37b7).

Then I go to admin page -> object -> members trying to add a member and dropdown is empty.
I had same issue with build 105 and corresponding members extension release.

**Comment by solverat** [comment]
please read the [installation guide](https://github.com/dachcom-digital/pimcore-members#installation). No classes will be installed automatically, you could use the install classes command though.

**Comment by geekdevs** [comment]
ah, yes that works, thank you

**Comment by geekdevs** [comment]
For future googles, that's how I could install it:

```
composer require dachcom-digital/members:dev-master
bin/console pimcore:bundle:enable MembersBundle
bin/console cache:clear
bin/console pimcore:bundle:install MembersBundle
bin/console members:install:class
```
