### ISSUE TITLE
Exception after installing Bundle

### ISSUE THREAD

**Issue by SGerry** [dachcom-digital/pimcore-members#32]
In members/src/MembersBundle/Manager/UserManager.php at line 39 the required path "/members" is not available directly after installation, so the getId() part throws an exception. (tested multiple times).
Can be solved by checking for existance and add the required folder when not exitsting or by installer routines.
(Pimcore 5.0.0|132)

**Comment by solverat** [comment]
that's weird, this folder gets installed during the install process:
https://github.com/dachcom-digital/pimcore-members/blob/dd06a313686411f5cff18f0cc719751960982387/src/MembersBundle/Tool/Install.php#L145
