### ISSUE TITLE
Admin register notification is sent to sign up user

### ISSUE THREAD

**Issue by gadget60** [dachcom-digital/pimcore-members#37]
I'm not sure if this is intended behaviour - although I can't see why it would make sense: 
If "post_register_type" is "confirm_by_admin" and "send_admin_mail_after_register" is true, the notification mail with the admin deep link is sent to the user that just signed up for a new account.

I would expect this mail being sent to an admin instead, which probably has to be defined in the email template settings. While this actually works, the signup user still receives a copy of this mail, because the "user notification" with "admin template" is hardcoded here:
https://github.com/dachcom-digital/pimcore-members/blob/6dd7f510c7bbe59369ed2f4c65ae31eac24b008b/src/MembersBundle/Mailer/Mailer.php#L103

I guess this is not desirable - am I wrong?

**Comment by solverat** [comment]
hey @gadget60. you're right of course. i just fixed that, please try it again (don't forget to add a recipient to the admin mail document).

**Comment by gadget60** [comment]
thx alot @solverat!

**Comment by gadget60** [comment]
hi @solverat 
Would you mind releasing a new version with this fix applied? As I see the latest stable version still is v2.0.1 from October 2017... Thank you!

**Comment by solverat** [comment]
hey @gadget60. Finally 2.1.0 has been released. :)
https://github.com/dachcom-digital/pimcore-members/releases/tag/v2.1.0

**Comment by gadget60** [comment]
Vielen Dank und Gruss!

Michael Reufer
Web-Entwickler

Brunner Medien AG
Arsenalstrasse 24
Postfach 1064
CH-6011 Kriens
www.bag.ch

m.reufer@bag.ch
T +41 41 318 34 22 Hotline
T +41 41 318 34 34

Von: Stefan Hagspiel [mailto:notifications@github.com]
Gesendet: Sonntag, 6. Mai 2018 15:40
An: dachcom-digital/pimcore-members
Cc: Reufer Michael; Mention
Betreff: Re: [dachcom-digital/pimcore-members] Admin register notification is sent to sign up user (#37)


hey @gadget60<https://github.com/gadget60>. Finally 2.1.0 has been released. :)
https://github.com/dachcom-digital/pimcore-members/releases/tag/v2.1.0
