### ISSUE TITLE
[improvement] render all forms in a consistent way without hardcoded HTML

### ISSUE THREAD

**Issue by LosHawlos** [dachcom-digital/pimcore-members#41]
Currenty the HTML of the forms is not generated in the same way for some forms.
For example login and password lost look different than the registration form and require some additional CSS.
Ideally all forms would use the Symfony form_theme for rendering.

**Comment by solverat** [comment]
This is going to be a major bc break but you're right. I'll check it out.

**Comment by solverat** [comment]
ping @LosHawlos.

**Comment by LosHawlos** [comment]
Sorry, was busy on other projects. I'l check this today.

**Comment by LosHawlos** [comment]
Looks good! Was able to reduce the amount of files that we have overwritten.
