### ISSUE TITLE
[improvement] Form to provide account deletion

### ISSUE THREAD

**Issue by LosHawlos** [dachcom-digital/pimcore-members#48]
I'm starting to implement a delete account form so users can terminate their account. I'l provide a PR when I'm done.

**Comment by solverat** [comment]
hey @LosHawlos. I just merged your PR. I also made some fixes: https://github.com/dachcom-digital/pimcore-members/commit/f89300561ab19f6f3c4c389caf68addfb9759b76

Thanks for your contribution! 👍
