### ISSUE TITLE
[EventListener] TreeListener not working before Pimcore 5.3

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-members#64]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? | yes
| RFC?             | yes

The TreeListener uses [two pimcore AdminEvents](https://github.com/dachcom-digital/pimcore-members/blob/master/src/MembersBundle/EventListener/TreeListener.php#L34-L35) that were [introduced with Pimcore 5.3](https://github.com/pimcore/pimcore/commit/9bb23a4bc2a20e0a0223389e57abcd8ceeaaceee). Therefore when updating Members with a Pimcore version prior to v5.3.0 it breaks the whole application.

```log
FatalThrowableError
Undefined class constant 'ASSET_TREE_GET_CHILDREN_BY_ID_PRE_SEND_DATA'
```

For now I reverted back to `dev-master#46e843a75677f6234b6441be71e38ff4626a01b7`

**Comment by solverat** [comment]
Hey @aarongerig, yes - that's annoying, sorry for that. I'll fix that today.

**Comment by aarongerig** [comment]
Hi @solverat, all good no worries – thank you!
