### ISSUE TITLE
Validation Translations

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-members#66]
| Q                | A
| ---------------- | -----
| Bug report?      | not really
| Feature request? | no
| BC Break report? | no
| RFC?             | no

With case https://github.com/dachcom-digital/pimcore-members/issues/45 the default validation domain has been reverted. But: Members still install Pimcore Shared Translations and they don't work out of the box. So it is unclear for the Developer how to use them. You can either change the validation translation domain to 'messages' or create a validations.yml translation file.

I think Members should supply a  default 'validations.yml' translation file and remove them from the shared translation.

**Comment by dkidd** [comment]
Thank you, @dpfaffenbauer, for raising this issue and suggesting a solution. Once again, you've saved me a bunch of time. 

I created validators.en.yml and validators.de.yml in app/Resources/translations, and the validation messages started working as expected.
[validators.zip](https://github.com/dachcom-digital/pimcore-members/files/2691177/validators.zip)

**Comment by solverat** [comment]
True. I'm going to remove all the `members.validation.*` entries from the frontend translation file and move it to a separate validations.yml file. BC should be no problem either.

**Comment by solverat** [comment]
done.
