### ISSUE TITLE
Consent for Admin Activate User

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-members#67]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

What if Members uses the consent data-type for activated by admin feature?

https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Data_Types/Consent.html

**Comment by solverat** [comment]
For that:
- we need to introduce a new field (consent) to the user data model + migration
- write a migration for existing users confirmed by admin

Since we fixed the admin confirmation issue (#79) this would be a good improvement without priority. However, feel free to provide a PR! 👍
