### ISSUE TITLE
Registration type depending on domain and locale

### ISSUE THREAD

**Issue by Sonja-Schubert** [dachcom-digital/pimcore-members#68]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Hi,
as far as I see the registration type is defined globally by 

members:
    # confirm_by_mail, confirm_by_admin, confirm_instant
    post_register_type: 'confirm_by_mail'

We have a pimcore project with one pimcore installation but several domain trees and inside of them several langugage trees. In this project some languages (= markets) of the website need one registration type and some of them needs another registration type.

It is possible to change the registration type depending on domain and locale? I saw the same can already be done for the email templates.

Kind regards,
Sonja

**Comment by solverat** [comment]
Hey @Sonja-Schubert. Thanks for your input. Unfortunately you're right, currently it's impossible to achieve this out of the box. To do so, we also should move `send_admin_mail_after_register` and `send_user_mail_after_confirmed` to a context sensitive section. 

However, i'm not sure how to handle situations like these. We could fire some events, but then we would have events in events which feels quite odd... There is also the context idea which we realized in our [toolbox bundle](https://github.com/dachcom-digital/pimcore-toolbox/blob/master/docs/15_Context.md) - could be an overhead though. 

The quick and dirty solution: override `PostConfirmationListener` and maybe the `UserChangeListener` class to change those action based on the master request context until we found a proper solution!
