### ISSUE TITLE
Cannot access protected property $groups

### ISSUE THREAD

**Issue by Sonja-Schubert** [dachcom-digital/pimcore-members#70]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Members Bundle Version 2.2.0 via composer
Pimcore Version Version 5.5.3 via composer

As soon as I click on a MembersUser object in Data Objects tree I get an HTTP 500 Error popup, see screenshot. I created and configured the MembersUser and MembersGroup classes as described in documentation on github. 
Result is that i cannot open any MemberUser Object and also cannot create any new one. Does it has something to do with the new pimcore version?

Kind regards,
Sonja

![bildschirmfoto 2018-11-26 um 14 58 31](https://user-images.githubusercontent.com/17587917/49018905-e71db780-f18c-11e8-81be-128fc01baf5f.png)

**Comment by solverat** [comment]
Hey Sonja. Yes, since pimcore 5.5 properties are protected now. I recently added a fix for this (https://github.com/dachcom-digital/pimcore-members/commit/46605c9e59338fac91eb6ad79b47a38c36c94e82), could you try it again with the latest dev-master?

**Comment by Sonja-Schubert** [comment]
Hi solverat,
thank you for the hint. With this patch it works for me.
Maybe it would make sense to create a new bugfix release including this fix because in my opinion it is not usable without the fix...
Thank you for your help and development, the bundle is great to work with!
Kind regards,
Sonja

**Comment by scrummer** [comment]
Hi Sonja

Here you go: https://github.com/dachcom-digital/pimcore-members/releases/tag/v2.2.1
