### ISSUE TITLE
[Feature] Custom storage path

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-members#71]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Is there a reason to permanently store all `User` objects inside `/members`? If not, I would like to be able to configure that in the bundle configs.

```
members:
    user:
        storage_path: /members # or something else
```

What do you think? If you want I could provide a PR for that.

**Comment by solverat** [comment]
Hey @aarongerig. I don't see any disadvantages, so yea: good idea - go ahead! 👍

**Comment by solverat** [comment]
done.
