### ISSUE TITLE
Validator constraints/properties only apply to MemberUser class

### ISSUE THREAD

**Issue by dkidd** [dachcom-digital/pimcore-members#76]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The MembersBundle includes a file, `Resources/config/validation/User.yml`, in which validator constraints and properties are defined for the `Pimcore\Model\DataObject\MembersUser` object. Unfortunately, if one is trying to use a different class name, these constraints and properties will not apply. As a consequence, there is no validation error if (for example) one tries to set a password that's too short.

To work around this problem, I copied the contents of the file into `AppBundle/Resources/config/validation.yml` and replaced `Pimcore\Model\DataObject\MembersUser` with my preferred class name, and that seems to have done the trick. It seems like there must be a better way, though...

**Comment by solverat** [comment]
Hey @dkidd, i just mapped the validation to the `UserInterface` which should fix your issue.
