### ISSUE TITLE
update to pimcore 5.6.0

### ISSUE THREAD

**Issue by iventura** [dachcom-digital/pimcore-members#81]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

by the update to pimcore 5.6.0 follow error appears:

  Error: Class MembersBundle\CoreExtension\GroupMultiselect contains 2 abstra  
  ct methods and must therefore be declared abstract or implement the remaini  
  ng methods (Pimcore\Model\DataObject\ClassDefinition\Data\Relations\Abstrac  
  tRelations::loadData, Pimcore\Model\DataObject\ClassDefinition\Data\Relatio  
  ns\AbstractRelations::prepareDataForPersistence)

Looks like too more abstract classes were added to Pimcore\Model\DataObject\ClassDefinition\Data\Relations\Abstrac  
  tRelations and they have to be implemented in the  MembersBundle\CoreExtension\GroupMultiselect

**Comment by iventura** [comment]
Hi guys,  and thank you a lot for the fix. I tried it already and have a new exception in the prepareDataForPersistence function, which calls getDataFromResource with the array of objects. The exception happens  by the line GroupMultiselect.php:169:  if ($element['type'] == 'object'):
Cannot use object of type Pimcore\Model\DataObject\MembersGroup as array

May be it will help you.

With the best regards,
Ivan

**Comment by solverat** [comment]
yes, i'm working on it.

**Comment by solverat** [comment]
this should be fine now.
