### ISSUE TITLE
REST Webservice API

### ISSUE THREAD

**Issue by binarykitchen** [dachcom-digital/pimcore-members#85]
Just a quick question: would it be possible to create users via Pimcore's REST Webservice API (https://pimcore.com/docs/5.x/Development_Documentation/Web_Services/index.html)

Like that we could implement the user registration page on a different server.

**Comment by solverat** [comment]
Hey @binarykitchen, yes that's possible. I just added some tests (https://github.com/dachcom-digital/pimcore-members/blob/master/tests/bundle_tests/rest/ObjectTest.php)
