### ISSUE TITLE
Update to Pimcore v5.6.0 not possible due to missing abstract methods

### ISSUE THREAD

**Issue by gahabkaFlorian** [dachcom-digital/pimcore-members#86]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Due to missing abstract methods in "dachcom-digital\members\src\MembersBundle\CoreExtension\GroupMultiselect.php" the update of pimcore to version 5.6.0 will fail.

SOLUTION:
Declare methods in "dachcom-digital\members\src\MembersBundle\CoreExtension\GroupMultiselect.php".

Missing function declaration
Pimcore\Model\DataObject\ClassDefinition\Data\Relations\AbstractRelations::loadData
Pimcore\Model\DataObject\ClassDefinition\Data\Relations\AbstractRelations::prepareDataForPersistence

**Comment by solverat** [comment]
already fixed in #81. please use current dev-master until we release 2.3.0.
