### ISSUE TITLE
Question on navigation

### ISSUE THREAD

**Issue by justbane** [dachcom-digital/pimcore-members#93]
I am not a twig fan - how do you do the navigation using the standard php nav builder?

my code would look like this

`$this->navigation()->buildNavigation($document, $mainNavStartNode);`

would I change that to?... `$this->members()->buildNavigation($document, $mainNavStartNode);`

**Comment by solverat** [comment]
@justbane, sorry to hear that (also because symfony is going to [drop](https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-templating-component-integration) the php template support).

Also, we're not supporting any PHP template driven implementations.
