### ISSUE TITLE
MembersUser groups field does not load/save in admin backend

### ISSUE THREAD

**Issue by GALCF** [dachcom-digital/pimcore-members#95]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

While updating Pimcore from 5.7.3 to 5.8.0 the groups field does not load correctly anymore.
The route `/admin/object/get` for a MembersUser returns `data.groups` as an empty string.

This seems to happen because of this commit:
https://github.com/pimcore/pimcore/commit/8a733d73ad5b4b3a6ccf231685cb9a589ac775f3#diff-e8108c94d4feb0213ffe581bd7d1303aR392
```diff
-       return $data;
+       return $data['data'];
```

Changing https://github.com/dachcom-digital/pimcore-members/blob/master/src/MembersBundle/CoreExtension/GroupMultiselect.php#L235 solves the issue for me, but I don't know the repercussions of this change and if it should only be changed for the loadData() function

```diff
-       return $elements;
+       return [
+           'data' => $elements,
+       ];
```

**Comment by solverat** [comment]
hey @GALCF, thanks for reporting. This should be fixed now (#96)!
