### ISSUE TITLE
members checks for duplicates in combination with cmf, on set cmf checkbox "active" and save

### ISSUE THREAD

**Issue by tobbert** [dachcom-digital/pimcore-members#99]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

![Bildschirmfoto 2019-06-09 um 09 03 00](https://user-images.githubusercontent.com/39373905/59156057-7b020180-8a95-11e9-89b1-8555804db0b0.png)

Hey,

I have something not so desired, it´s not really a bug, but could lead to problems.
If set a customer (member) active (checkbox „active“ , checkbox comes with cmf-bundle -> customer class), and save the customer, the members bundle checks for duplicates with firstname AND lastname.

However, it is possible that customers (members) with the same first and last name exist!?

br

**Comment by solverat** [comment]
@tobbert: MembersBundle does not apply any checks against duplicates. This comes straight from the CMF:

https://github.com/pimcore/customer-data-framework/blob/24eedba5da2bccc50e12b26e08d8e437a7483790/src/CustomerSaveValidator/DefaultCustomerSaveValidator.php#L100-L119

**Comment by tobbert** [comment]
Hello,

thanks, I got it.

br
